name: C/C++ CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Pre-build
      run: |
           apt install ffmpeg
           mkdir bin

    - name: Compilation
      run: make

    - name: Post-Build
      run: |
           cat build.log
