name: C/C++ CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Configure
      run: |
           mkdir bin
           pwd
           ls -all
    - name: Compilation
      run: make
    - name: Logfile
      run: |
           ls -all
           cat build.log
